{"name": "Проверка невозможности регистрации 2х курьеров c одинаковым логином", "status": "passed", "description": "Проверяем, что запрос на регистрацию курьера с использованием уже зарегистрированного логина вернет код 409 и сообщение {\"code\": 409, \"message\": \"Этот логин уже используется. Попробуйте другой.\"}", "start": 1739117859821, "stop": 1739117860017, "uuid": "1b267682-41a1-4616-b063-a2b61718916c", "historyId": "ac08b39659c0f3a054d5718941834dc5", "testCaseId": "ac08b39659c0f3a054d5718941834dc5", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_two_couriers_with_same_login_code409", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "MaryBook"}, {"name": "thread", "value": "8572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}